### PR TITLE
added support for multiple monitors

### PR DESCRIPTION
**Pull request by egigoka**
My first experience with C++. And first pull request. Sorry for global variables. I think you can do it better, but it works perfectly on multi-monitor workstations now! ^_^

### CODE REVIEW

**Comment by mlong212** [comment]
Very new to "building / compiling". I tried downloading the source and adding in your changes. Any idea why Visual studio 2019 would error with:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	 va_start argument must not have reference type and must not be parenthesized	stacky	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\vadefs.h	151

**Comment by kintaro1981** [comment]
@pawelt are you still supporting stacky? how about adding this pull request?

@egigoka how about fork in your github and build it?

**Comment by egigoka** [comment]
> @pawelt are you still supporting stacky? how about adding this pull request?
> 
> @egigoka how about fork in your github and build it?

I'll try at home :)

**Comment by pawelt** [comment]
Sorry for the a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)

**Pull request closed without merging**
